export const DEFAULT_CONFIG = {
    LOGGING: false,
    MAX_TOKEN_SIZE: 500,
    SIMILARITY_THRESHOLD: 0.5,
    DYNAMIC_THRESHOLD_LOWER_BOUND: 0.4,
    DYNAMIC_THRESHOLD_UPPER_BOUND: 0.8,
    NUM_SIMILARITY_SENTENCES_LOOKAHEAD: 3,
    COMBINE_CHUNKS: true,
    COMBINE_CHUNKS_SIMILARITY_THRESHOLD: 0.5,
    MAX_PASSES: 5, // Default max passes for iterative optimization

    // Output
    RETURN_EMBEDDING: true,
    RETURN_TOKEN_LENGTH: true,
    CHUNK_PREFIX: '',
    EXCLUDE_CHUNK_PREFIX_IN_RESULTS: false,
};